apiVersion: v1
kind: Service
metadata:
  name: aspnetapp
  labels:
    app: aspnetapp
    service: aspnetapp
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: aspnetapp
